# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/streams/*"
  to = "https://api.stocktwits.com/api/2/streams:splat"
  status = 200
  force = true

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
